-- Volcado del esquema REAL de control_alimentadores.db (fuente de verdad)
-- Generado para la migracion a Streamlit + Turso -- ver plan de migracion.
-- NO editar 2_migrar_datos.py como referencia de esquema: esta desactualizado.

-- Tabla NUEVA (no existe en la app de escritorio, que guarda esto en
-- app/config/usuarios.json sin contrasena, confiando en el usuario de
-- Windows). Se agrega en la Fase 3 de la migracion para el login real
-- por usuario+contrasena de la app web.
CREATE TABLE usuarios (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL COLLATE NOCASE,
    nombre TEXT,
    rol TEXT NOT NULL CHECK(rol IN ('ADMIN','EDITOR','CONSULTA')),
    password_hash TEXT NOT NULL,
    activo INTEGER DEFAULT 1,
    creado_en TEXT DEFAULT (datetime('now'))
);

-- Permisos granulares por pagina/usuario (capa nueva, agregada junto al
-- `rol` de arriba -- no lo reemplaza). `rol` queda para identidad/
-- visualizacion; el gate real de cada pagina (menu + backend) pasa por
-- aca. `pagina_id` es el slug estable definido en core/auth.PAGINAS.
-- Sin fila para un (usuario, pagina) = 'ninguno' (principio de menor
-- privilegio para usuarios nuevos) -- ver core/auth.get_permiso().
CREATE TABLE permisos_usuario (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    usuario_id INTEGER NOT NULL REFERENCES usuarios(id),
    pagina_id TEXT NOT NULL,
    nivel_acceso TEXT NOT NULL CHECK(nivel_acceso IN ('ninguno','lectura','edicion')),
    UNIQUE(usuario_id, pagina_id)
);

CREATE TABLE ALIMENTADORES (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    ALIMENTADOR TEXT UNIQUE NOT NULL,
    SUBESTACION TEXT,
    TIPO_ALIMENTADOR TEXT DEFAULT 'Alimentador',
    MES_PLANIFICADO TEXT,
    ORDEN_ATENCION INTEGER,
    SELECCION_PLUZ TEXT DEFAULT 'TOP 101',
    DENSIDAD TEXT,
    ESTADO_TRABAJO_MT TEXT DEFAULT 'POR TRABAJAR',
    ESTADO_TRABAJO_BT TEXT DEFAULT 'POR TRABAJAR',
    ESTADO_PINZADO TEXT DEFAULT 'POR INICIAR',
    ESTADO_ANALISIS_CSG TEXT DEFAULT 'POR TRABAJAR',
    N_SEDS INTEGER DEFAULT 0,
    CLIENTES_MAX_MT INTEGER DEFAULT 0,
    CLIENTES_LIB_PEAJES INTEGER DEFAULT 0,
    CLIENTES_NO_UBI INTEGER DEFAULT 0,
    PERDIDA_MT_REF REAL,
    PERDIDA_COMERCIAL_PROM REAL,
    FECHA_INICIO_PINZADO TEXT,
    FECHA_FIN_PINZADO TEXT,
    PLANO_NODOS TEXT,
    A_LOSS REAL,
    -- Contadores actualizados por triggers
    NODOS_SOSPECHOSOS INTEGER DEFAULT 0,
    TOTAL_ASIGNADOS_TOTA INTEGER DEFAULT 0,
    TOTAL_INSTALADOS_TOTA INTEGER DEFAULT 0,
    TOTAL_IMP_TOTA INTEGER DEFAULT 0,
    TOTAL_LECTURAS_RECOGER INTEGER DEFAULT 0,
    TOTAL_EFECTIVOS_LECTURA INTEGER DEFAULT 0,
    TOTAL_EFECTIVOS_PINZADO INTEGER DEFAULT 0,
    TOTAL_IMPEDIMENTOS_LEC INTEGER DEFAULT 0,
    TOTAL_IRREGULARIDADES INTEGER DEFAULT 0,
    -- Auditoría
    ESTADO_REGISTRO TEXT DEFAULT 'ALTA',
    CREADO_POR TEXT DEFAULT 'MIGRACION',
    FECHA_CREACION TEXT DEFAULT (datetime('now','localtime')),
    MODIFICADO_POR TEXT,
    FECHA_MODIFICACION TEXT,
    DADO_DE_BAJA_POR TEXT,
    FECHA_BAJA TEXT,
    MOTIVO_BAJA TEXT
, TOTAL_CASOS_INST_TOTA INTEGER DEFAULT 0, ESTADO_LECTURAS TEXT GENERATED ALWAYS AS (
            CASE
                WHEN (COALESCE(TOTAL_IMPEDIMENTOS_LEC,0) + COALESCE(TOTAL_EFECTIVOS_LECTURA,0) + COALESCE(TOTAL_EFECTIVOS_PINZADO,0))
                     = COALESCE(TOTAL_LECTURAS_RECOGER,0)
                THEN 'CERRADO'
                WHEN (COALESCE(TOTAL_IMPEDIMENTOS_LEC,0) + COALESCE(TOTAL_EFECTIVOS_LECTURA,0) + COALESCE(TOTAL_EFECTIVOS_PINZADO,0)) > 0
                     AND (COALESCE(TOTAL_IMPEDIMENTOS_LEC,0) + COALESCE(TOTAL_EFECTIVOS_LECTURA,0) + COALESCE(TOTAL_EFECTIVOS_PINZADO,0))
                         < COALESCE(TOTAL_LECTURAS_RECOGER,0)
                THEN 'EN CURSO'
                ELSE ''
            END
        ) VIRTUAL, ESTADO_INST_TOTAS TEXT GENERATED ALWAYS AS (
            CASE
                WHEN COALESCE(TOTAL_INSTALADOS_TOTA,0) = COALESCE(TOTAL_CASOS_INST_TOTA,0)
                THEN 'CERRADO'
                WHEN (COALESCE(TOTAL_IMP_TOTA,0) + COALESCE(TOTAL_INSTALADOS_TOTA,0)) = COALESCE(TOTAL_CASOS_INST_TOTA,0)
                THEN 'CERRADO CON IMP'
                WHEN (COALESCE(TOTAL_IMP_TOTA,0) + COALESCE(TOTAL_INSTALADOS_TOTA,0)) > 0
                     AND (COALESCE(TOTAL_IMP_TOTA,0) + COALESCE(TOTAL_INSTALADOS_TOTA,0)) < COALESCE(TOTAL_CASOS_INST_TOTA,0)
                THEN 'EN CURSO'
                ELSE ''
            END
        ) VIRTUAL, N_TOTAS INTEGER DEFAULT 0, TOTAS_PENDIENTES INTEGER DEFAULT 0, TOTAL_CLIENTES_MT INTEGER GENERATED ALWAYS AS (
            COALESCE(N_TOTAS,0) + COALESCE(TOTAS_PENDIENTES,0) + COALESCE(CLIENTES_MAX_MT,0)
            + COALESCE(CLIENTES_LIB_PEAJES,0) + COALESCE(CLIENTES_NO_UBI,0)
        ) VIRTUAL);

CREATE TABLE INSTALACIONES_TOTAS (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    alimentador_id INTEGER NOT NULL REFERENCES ALIMENTADORES(id),
    ALIMENTADOR TEXT NOT NULL,
    COD_PUNTO_MEDICION TEXT NOT NULL,
    COD_TRAFO TEXT,
    TIPO_CONSTRUCCION TEXT,
    ZONA TEXT,
    PRIORIDAD INTEGER,
    MES_PLANIFICADO TEXT,
    PLAZO_FINAL TEXT,
    ESTADO_CONTROL TEXT DEFAULT 'POR TRABAJAR',
    ESTADO_INSTALACION TEXT DEFAULT 'NO ASIGNADO',
    SUBESTADO TEXT,
    MEDIDOR_SB TEXT,
    MARCA TEXT,
    TIPO_FINAL TEXT DEFAULT 'SED',
    FECHA_INTERVENCION TEXT,
    MOTIVO_UNIFICADO TEXT,
    DETALLE_CAMPO TEXT,
    ESTADO_REGISTRO TEXT DEFAULT 'ALTA',
    CREADO_POR TEXT DEFAULT 'MIGRACION',
    FECHA_CREACION TEXT DEFAULT (datetime('now','localtime')),
    MODIFICADO_POR TEXT,
    FECHA_MODIFICACION TEXT,
    DADO_DE_BAJA_POR TEXT,
    FECHA_BAJA TEXT,
    MOTIVO_BAJA TEXT,
    UNIQUE(ALIMENTADOR, COD_PUNTO_MEDICION)
);

CREATE TABLE IRREGULARIDADES (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    -- Nullable (antes NOT NULL): una fila puede llegar con un ALIMENTADOR
    -- que todavia no existe en el maestro (ver ORIGEN mas abajo) -- no se
    -- descarta la fila por eso, se guarda con alimentador_id=NULL hasta
    -- que el maestro lo tenga.
    alimentador_id INTEGER REFERENCES ALIMENTADORES(id),
    ALIMENTADOR TEXT NOT NULL,
    NODO INTEGER NOT NULL,
    -- Ex CONCA, renombrada a KEY (pedido explicito) -- es la clave real de
    -- esta tabla, viene tal cual del Excel origen (no se deriva en este
    -- pipeline), por eso es estable entre cargas. "KEY" es palabra
    -- reservada de SQL: toda referencia en el codigo la cita entre
    -- comillas dobles.
    "KEY" TEXT NOT NULL UNIQUE,
    SUM_CLIENTE INTEGER,
    COD_PUNTO_MEDICION TEXT,
    CATEGORIA TEXT,
    TIPO_HURTO TEXT,
    TENSION TEXT,
    TIPO_CLIENTE TEXT,
    CONDICION_CLIENTE TEXT,
    FECHA_ASIG_INSP TEXT,
    FECHA_NORMALIZACION TEXT,
    -- Auditado junto con el fix de SOSPECHAS_BT.PERDIDA_KWH (operando vacio
    -- tratado como 0): NO aplica aca. Una fecha faltante no es "cero dias",
    -- es "no se puede calcular" -- tratarla como 0 daria una diferencia de
    -- dias falsa, no "sin dato". Se deja exigiendo ambas fechas.
    DIAS_CIERRE INTEGER GENERATED ALWAYS AS (
        CASE WHEN FECHA_NORMALIZACION IS NOT NULL AND FECHA_ASIG_INSP IS NOT NULL
        THEN CAST(julianday(FECHA_NORMALIZACION) - julianday(FECHA_ASIG_INSP) AS INTEGER)
        ELSE NULL END
    ) STORED,
    ESTADO_FOCALIZACION TEXT,
    RECUPERO_MWH REAL,
    MESES_CNR REAL,
    -- Auditado junto con SOSPECHAS_BT.PERDIDA_KWH: NO aplica aca tampoco.
    -- Es un promedio mensual (division) -- sin RECUPERO_MWH o sin MESES_CNR
    -- no hay tasa que calcular ("sin dato" real), tratar cualquiera de los
    -- dos como 0 daria una tasa falsa (0 o division por cero ya evitada).
    RECUPERO_MWH_MES REAL GENERATED ALWAYS AS (
        CASE WHEN MESES_CNR IS NOT NULL AND MESES_CNR != 0 AND RECUPERO_MWH IS NOT NULL
        THEN ROUND(RECUPERO_MWH / MESES_CNR, 4) ELSE NULL END
    ) STORED,
    ESTADO_CNR TEXT,
    IMPACTO_ANO_MWH REAL,
    MOTIVO_RECHAZO TEXT,
    OBSERVACIONES TEXT,
    -- Columna nueva, mantenida por trigger (trg_irr_ins/trg_irr_upd), NO
    -- por la app: 'PROY-101' si ALIMENTADOR existe en el maestro
    -- ALIMENTADORES al momento del insert/update, 'NO INFORMADO' si no.
    -- No es GENERATED porque SQLite no permite subqueries en columnas
    -- generadas (necesita mirar OTRA tabla) -- se recalcula via trigger,
    -- mismo patron que ESTADO_RE/PERIODO_PLANIF en SOSPECHAS_BT. Se
    -- autocorrige a 'PROY-101' sin intervencion manual cuando el
    -- alimentador huerfano se agrega despues a ALIMENTADORES, via
    -- trg_alim_ins_origen.
    ORIGEN TEXT,
    ESTADO_REGISTRO TEXT DEFAULT 'ALTA',
    CREADO_POR TEXT DEFAULT 'MIGRACION',
    FECHA_CREACION TEXT DEFAULT (datetime('now','localtime')),
    MODIFICADO_POR TEXT,
    FECHA_MODIFICACION TEXT,
    DADO_DE_BAJA_POR TEXT,
    FECHA_BAJA TEXT,
    MOTIVO_BAJA TEXT
);

CREATE TABLE LECTURAS (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    alimentador_id INTEGER NOT NULL REFERENCES ALIMENTADORES(id),
    ALIMENTADOR TEXT NOT NULL,
    COD_PUNTO_MEDICION TEXT NOT NULL,
    PERIODO TEXT NOT NULL,
    TIPO TEXT,
    COD_TRAFO TEXT,
    MEDIDOR_SB TEXT,
    MARCA TEXT,
    ESTADO_LECTURA TEXT DEFAULT 'ASIGNADO',
    FECHA_EXTRACCION TEXT,
    MOTIVO_UNIFICADO TEXT,
    DETALLE_CAMPO TEXT,
    EECC TEXT,
    ESTADO_REGISTRO TEXT DEFAULT 'ALTA',
    CREADO_POR TEXT DEFAULT 'MIGRACION',
    FECHA_CREACION TEXT DEFAULT (datetime('now','localtime')),
    MODIFICADO_POR TEXT,
    FECHA_MODIFICACION TEXT,
    DADO_DE_BAJA_POR TEXT,
    FECHA_BAJA TEXT,
    MOTIVO_BAJA TEXT,
    UNIQUE(ALIMENTADOR, COD_PUNTO_MEDICION, PERIODO)
);

CREATE TABLE LOG_ACCIONES (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    tabla TEXT NOT NULL,
    registro_id INTEGER,
    accion TEXT NOT NULL,
    descripcion TEXT,
    usuario TEXT,
    fecha TEXT DEFAULT (datetime('now','localtime'))
);

CREATE TABLE SOSPECHAS_BT (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    alimentador_id INTEGER NOT NULL REFERENCES ALIMENTADORES(id),
    ALIMENTADOR TEXT NOT NULL,
    NODO INTEGER NOT NULL,
    SED TEXT NOT NULL,
    PERIODO_PLANIF TEXT NOT NULL,
    FECHA_ASIGNACION TEXT,
    MEDIDOR_TOTALIZADOR TEXT,
    CONSUMO_TOTALIZADOR REAL,
    CONSUMO_CLIENTES REAL,
    -- CONSUMO_CLIENTES vacio se trata como 0 (regla de negocio: un SED sin
    -- clientes informados igual tiene perdida = todo el consumo del
    -- totalizador). CONSUMO_TOTALIZADOR si sigue siendo obligatorio -- sin
    -- el total no hay nada que calcular, a diferencia de sin clientes.
    -- VIRTUAL (no STORED): SQLite no permite agregar una columna STORED via
    -- ALTER TABLE a una tabla con filas (probado en produccion, 1935 filas,
    -- fallo con "cannot add a STORED column"); VIRTUAL se calcula al leer,
    -- sin backfill, y funciona igual en una tabla vacia o poblada.
    PERDIDA_KWH REAL GENERATED ALWAYS AS (
        CASE WHEN CONSUMO_TOTALIZADOR IS NOT NULL
        THEN ROUND(CONSUMO_TOTALIZADOR - COALESCE(CONSUMO_CLIENTES, 0), 2) ELSE NULL END
    ) VIRTUAL,
    PERDIDA_PCT REAL GENERATED ALWAYS AS (
        CASE WHEN CONSUMO_TOTALIZADOR IS NOT NULL AND CONSUMO_TOTALIZADOR != 0
        THEN ROUND((CONSUMO_TOTALIZADOR - COALESCE(CONSUMO_CLIENTES, 0)) / CONSUMO_TOTALIZADOR * 100, 2) ELSE NULL END
    ) VIRTUAL,
    ESTADO_ACTIVIDAD TEXT,
    ESTADO_FOCALIZACION TEXT,
    -- Agregadas para el segmento "Analisis de alimentadores por nodos BT"
    -- del Dashboard (columnas 'STATUS DE CONTEO SED' y 'Energia kWh Rec/Mes'
    -- del Excel maestro, BD SOSPECHA BT; existian en el Excel pero se
    -- habian omitido en la migracion original).
    STATUS_CONTEO_SED TEXT,
    ENERGIA_KWH_REC_MES REAL,
    RESPONSABLE_INSP TEXT,
    OBSERVACIONES TEXT,
    RESUMEN_HURTO TEXT,
    ESTADO_RE TEXT,
    ESTADO_ANALISIS_CSG TEXT,
    ESTADO_REGISTRO TEXT DEFAULT 'ALTA',
    CREADO_POR TEXT DEFAULT 'MIGRACION',
    FECHA_CREACION TEXT DEFAULT (datetime('now','localtime')),
    MODIFICADO_POR TEXT,
    FECHA_MODIFICACION TEXT,
    DADO_DE_BAJA_POR TEXT,
    FECHA_BAJA TEXT,
    MOTIVO_BAJA TEXT, RIESGO TEXT GENERATED ALWAYS AS (
            CASE
                WHEN PERDIDA_KWH IS NULL THEN 'SIN DATOS'
                WHEN PERDIDA_KWH < 0 THEN 'NEGATIVO'
                WHEN PERDIDA_KWH < 3000 THEN 'CONTROLADO'
                WHEN PERDIDA_KWH < 5000 THEN 'BAJO'
                WHEN PERDIDA_KWH < 10000 THEN 'MEDIO'
                WHEN PERDIDA_KWH > 10000 THEN 'ALTO'
                ELSE 'SIN DATOS'
            END
        ) VIRTUAL,
    UNIQUE(ALIMENTADOR, NODO, SED, PERIODO_PLANIF)
);

CREATE TABLE SOSPECHAS_MT (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    alimentador_id INTEGER NOT NULL REFERENCES ALIMENTADORES(id),
    ALIMENTADOR TEXT NOT NULL,
    NODO INTEGER NOT NULL,
    PERIODO_PLANIF TEXT,
    CORRIENTE_A REAL,
    FECHA_CARGA TEXT,
    ESTADO_ACTIVIDAD TEXT,
    ESTADO_RE TEXT,
    ESTADO_INSP TEXT,
    OBVS_ANALISIS TEXT,
    OBSERVACION TEXT,
    ESTADO_REGISTRO TEXT DEFAULT 'ALTA',
    CREADO_POR TEXT DEFAULT 'MIGRACION',
    FECHA_CREACION TEXT DEFAULT (datetime('now','localtime')),
    MODIFICADO_POR TEXT,
    FECHA_MODIFICACION TEXT,
    DADO_DE_BAJA_POR TEXT,
    FECHA_BAJA TEXT,
    MOTIVO_BAJA TEXT,
    UNIQUE(ALIMENTADOR, NODO)
);

CREATE TRIGGER trg_alim_upd AFTER UPDATE ON ALIMENTADORES BEGIN
            UPDATE SOSPECHAS_MT SET PERIODO_PLANIF=NEW.MES_PLANIFICADO WHERE ALIMENTADOR=NEW.ALIMENTADOR;
            UPDATE SOSPECHAS_BT SET PERIODO_PLANIF=COALESCE(NEW.MES_PLANIFICADO,'') WHERE ALIMENTADOR=NEW.ALIMENTADOR;
        END;

CREATE TRIGGER trg_inst_del AFTER DELETE ON INSTALACIONES_TOTAS BEGIN
            UPDATE ALIMENTADORES SET
                TOTAL_ASIGNADOS_TOTA=(SELECT COUNT(*) FROM INSTALACIONES_TOTAS WHERE ALIMENTADOR=OLD.ALIMENTADOR AND ESTADO_INSTALACION='ASIGNADO' AND ESTADO_REGISTRO='ALTA'),
                TOTAL_INSTALADOS_TOTA=(SELECT COUNT(*) FROM INSTALACIONES_TOTAS WHERE ALIMENTADOR=OLD.ALIMENTADOR AND ESTADO_INSTALACION='INSTALADO' AND ESTADO_REGISTRO='ALTA'),
                TOTAL_IMP_TOTA=(SELECT COUNT(*) FROM INSTALACIONES_TOTAS WHERE ALIMENTADOR=OLD.ALIMENTADOR AND ESTADO_INSTALACION='IMPEDIMENTO' AND ESTADO_REGISTRO='ALTA'),
                TOTAL_CASOS_INST_TOTA=(SELECT COUNT(*) FROM INSTALACIONES_TOTAS WHERE ALIMENTADOR=OLD.ALIMENTADOR AND ESTADO_REGISTRO='ALTA')
            WHERE ALIMENTADOR=OLD.ALIMENTADOR;
            UPDATE INSTALACIONES_TOTAS SET ESTADO_CONTROL=(SELECT ESTADO_INST_TOTAS FROM ALIMENTADORES WHERE ALIMENTADOR=OLD.ALIMENTADOR)
            WHERE ALIMENTADOR=OLD.ALIMENTADOR;
        END;

CREATE TRIGGER trg_inst_ins
            AFTER INSERT ON INSTALACIONES_TOTAS BEGIN
                UPDATE ALIMENTADORES SET
                    TOTAL_ASIGNADOS_TOTA=(SELECT COUNT(*) FROM INSTALACIONES_TOTAS WHERE ALIMENTADOR=NEW.ALIMENTADOR AND ESTADO_INSTALACION='ASIGNADO' AND ESTADO_REGISTRO='ALTA'),
                    TOTAL_INSTALADOS_TOTA=(SELECT COUNT(*) FROM INSTALACIONES_TOTAS WHERE ALIMENTADOR=NEW.ALIMENTADOR AND ESTADO_INSTALACION='INSTALADO' AND ESTADO_REGISTRO='ALTA'),
                    TOTAL_IMP_TOTA=(SELECT COUNT(*) FROM INSTALACIONES_TOTAS WHERE ALIMENTADOR=NEW.ALIMENTADOR AND ESTADO_INSTALACION='IMPEDIMENTO' AND ESTADO_REGISTRO='ALTA'),
                    TOTAL_CASOS_INST_TOTA=(SELECT COUNT(*) FROM INSTALACIONES_TOTAS WHERE ALIMENTADOR=NEW.ALIMENTADOR AND ESTADO_REGISTRO='ALTA')
                WHERE ALIMENTADOR=NEW.ALIMENTADOR;
                UPDATE INSTALACIONES_TOTAS SET ESTADO_CONTROL=(SELECT ESTADO_INST_TOTAS FROM ALIMENTADORES WHERE ALIMENTADOR=NEW.ALIMENTADOR)
                WHERE ALIMENTADOR=NEW.ALIMENTADOR;
            END;

CREATE TRIGGER trg_inst_upd
            AFTER UPDATE ON INSTALACIONES_TOTAS BEGIN
                UPDATE ALIMENTADORES SET
                    TOTAL_ASIGNADOS_TOTA=(SELECT COUNT(*) FROM INSTALACIONES_TOTAS WHERE ALIMENTADOR=NEW.ALIMENTADOR AND ESTADO_INSTALACION='ASIGNADO' AND ESTADO_REGISTRO='ALTA'),
                    TOTAL_INSTALADOS_TOTA=(SELECT COUNT(*) FROM INSTALACIONES_TOTAS WHERE ALIMENTADOR=NEW.ALIMENTADOR AND ESTADO_INSTALACION='INSTALADO' AND ESTADO_REGISTRO='ALTA'),
                    TOTAL_IMP_TOTA=(SELECT COUNT(*) FROM INSTALACIONES_TOTAS WHERE ALIMENTADOR=NEW.ALIMENTADOR AND ESTADO_INSTALACION='IMPEDIMENTO' AND ESTADO_REGISTRO='ALTA'),
                    TOTAL_CASOS_INST_TOTA=(SELECT COUNT(*) FROM INSTALACIONES_TOTAS WHERE ALIMENTADOR=NEW.ALIMENTADOR AND ESTADO_REGISTRO='ALTA')
                WHERE ALIMENTADOR=NEW.ALIMENTADOR;
                UPDATE INSTALACIONES_TOTAS SET ESTADO_CONTROL=(SELECT ESTADO_INST_TOTAS FROM ALIMENTADORES WHERE ALIMENTADOR=NEW.ALIMENTADOR)
                WHERE ALIMENTADOR=NEW.ALIMENTADOR;
            END;

CREATE TRIGGER trg_irr_del AFTER DELETE ON IRREGULARIDADES BEGIN
            UPDATE ALIMENTADORES SET TOTAL_IRREGULARIDADES=(SELECT COUNT(*) FROM IRREGULARIDADES WHERE ALIMENTADOR=OLD.ALIMENTADOR AND ESTADO_REGISTRO='ALTA')
            WHERE ALIMENTADOR=OLD.ALIMENTADOR;
        END;

CREATE TRIGGER trg_irr_ins AFTER INSERT ON IRREGULARIDADES BEGIN
    UPDATE ALIMENTADORES SET TOTAL_IRREGULARIDADES=(SELECT COUNT(*) FROM IRREGULARIDADES WHERE ALIMENTADOR=NEW.ALIMENTADOR AND ESTADO_REGISTRO='ALTA') WHERE ALIMENTADOR=NEW.ALIMENTADOR;
    UPDATE IRREGULARIDADES SET
        alimentador_id=(SELECT id FROM ALIMENTADORES WHERE UPPER(ALIMENTADOR)=UPPER(NEW.ALIMENTADOR)),
        ORIGEN=CASE WHEN (SELECT id FROM ALIMENTADORES WHERE UPPER(ALIMENTADOR)=UPPER(NEW.ALIMENTADOR)) IS NOT NULL
               THEN 'PROY-101' ELSE 'NO INFORMADO' END
    WHERE id=NEW.id;
END;

CREATE TRIGGER trg_irr_upd AFTER UPDATE ON IRREGULARIDADES BEGIN
    UPDATE ALIMENTADORES SET TOTAL_IRREGULARIDADES=(SELECT COUNT(*) FROM IRREGULARIDADES WHERE ALIMENTADOR=NEW.ALIMENTADOR AND ESTADO_REGISTRO='ALTA') WHERE ALIMENTADOR=NEW.ALIMENTADOR;
    UPDATE IRREGULARIDADES SET
        alimentador_id=(SELECT id FROM ALIMENTADORES WHERE UPPER(ALIMENTADOR)=UPPER(NEW.ALIMENTADOR)),
        ORIGEN=CASE WHEN (SELECT id FROM ALIMENTADORES WHERE UPPER(ALIMENTADOR)=UPPER(NEW.ALIMENTADOR)) IS NOT NULL
               THEN 'PROY-101' ELSE 'NO INFORMADO' END
    WHERE id=NEW.id;
END;

-- Nuevo: cuando un alimentador huerfano se agrega recien al maestro
-- ALIMENTADORES, corrige de una sola vez todas las filas de IRREGULARIDADES
-- que estaban esperando por el (ORIGEN='NO INFORMADO') -- sin esto, esas
-- filas quedarian con ORIGEN desactualizado hasta que alguien las edite a
-- mano (pedido explicito: se autocorrige solo, sin intervencion manual).
CREATE TRIGGER trg_alim_ins_origen AFTER INSERT ON ALIMENTADORES BEGIN
    UPDATE IRREGULARIDADES SET alimentador_id=NEW.id, ORIGEN='PROY-101'
    WHERE UPPER(ALIMENTADOR)=UPPER(NEW.ALIMENTADOR) AND ORIGEN='NO INFORMADO';
END;

CREATE TRIGGER trg_lec_del AFTER DELETE ON LECTURAS BEGIN
            UPDATE ALIMENTADORES SET
                TOTAL_LECTURAS_RECOGER=(SELECT COUNT(*) FROM LECTURAS WHERE ALIMENTADOR=OLD.ALIMENTADOR AND ESTADO_REGISTRO='ALTA'),
                TOTAL_EFECTIVOS_LECTURA=(SELECT COUNT(*) FROM LECTURAS WHERE ALIMENTADOR=OLD.ALIMENTADOR AND ESTADO_LECTURA='EFECTIVO LECTURA' AND ESTADO_REGISTRO='ALTA'),
                TOTAL_EFECTIVOS_PINZADO=(SELECT COUNT(*) FROM LECTURAS WHERE ALIMENTADOR=OLD.ALIMENTADOR AND ESTADO_LECTURA='EFECTIVO PINZADO' AND ESTADO_REGISTRO='ALTA'),
                TOTAL_IMPEDIMENTOS_LEC=(SELECT COUNT(*) FROM LECTURAS WHERE ALIMENTADOR=OLD.ALIMENTADOR AND ESTADO_LECTURA='IMPEDIMENTO' AND ESTADO_REGISTRO='ALTA')
            WHERE ALIMENTADOR=OLD.ALIMENTADOR;
        END;

CREATE TRIGGER trg_lec_ins AFTER INSERT ON LECTURAS BEGIN
    UPDATE ALIMENTADORES SET
        TOTAL_LECTURAS_RECOGER=(SELECT COUNT(*) FROM LECTURAS WHERE ALIMENTADOR=NEW.ALIMENTADOR AND ESTADO_REGISTRO='ALTA'),
        TOTAL_EFECTIVOS_LECTURA=(SELECT COUNT(*) FROM LECTURAS WHERE ALIMENTADOR=NEW.ALIMENTADOR AND ESTADO_LECTURA='EFECTIVO LECTURA' AND ESTADO_REGISTRO='ALTA'),
        TOTAL_EFECTIVOS_PINZADO=(SELECT COUNT(*) FROM LECTURAS WHERE ALIMENTADOR=NEW.ALIMENTADOR AND ESTADO_LECTURA='EFECTIVO PINZADO' AND ESTADO_REGISTRO='ALTA'),
        TOTAL_IMPEDIMENTOS_LEC=(SELECT COUNT(*) FROM LECTURAS WHERE ALIMENTADOR=NEW.ALIMENTADOR AND ESTADO_LECTURA='IMPEDIMENTO' AND ESTADO_REGISTRO='ALTA')
    WHERE ALIMENTADOR=NEW.ALIMENTADOR; END;

CREATE TRIGGER trg_lec_upd AFTER UPDATE ON LECTURAS BEGIN
    UPDATE ALIMENTADORES SET
        TOTAL_LECTURAS_RECOGER=(SELECT COUNT(*) FROM LECTURAS WHERE ALIMENTADOR=NEW.ALIMENTADOR AND ESTADO_REGISTRO='ALTA'),
        TOTAL_EFECTIVOS_LECTURA=(SELECT COUNT(*) FROM LECTURAS WHERE ALIMENTADOR=NEW.ALIMENTADOR AND ESTADO_LECTURA='EFECTIVO LECTURA' AND ESTADO_REGISTRO='ALTA'),
        TOTAL_EFECTIVOS_PINZADO=(SELECT COUNT(*) FROM LECTURAS WHERE ALIMENTADOR=NEW.ALIMENTADOR AND ESTADO_LECTURA='EFECTIVO PINZADO' AND ESTADO_REGISTRO='ALTA'),
        TOTAL_IMPEDIMENTOS_LEC=(SELECT COUNT(*) FROM LECTURAS WHERE ALIMENTADOR=NEW.ALIMENTADOR AND ESTADO_LECTURA='IMPEDIMENTO' AND ESTADO_REGISTRO='ALTA')
    WHERE ALIMENTADOR=NEW.ALIMENTADOR; END;

CREATE TRIGGER trg_sbt_ins
            AFTER INSERT ON SOSPECHAS_BT BEGIN
                UPDATE SOSPECHAS_BT SET
                    PERIODO_PLANIF=COALESCE((SELECT MES_PLANIFICADO FROM ALIMENTADORES WHERE ALIMENTADOR=NEW.ALIMENTADOR), ''),
                    ESTADO_RE=COALESCE(
                        (SELECT ESTADO_ACTIVIDAD FROM SOSPECHAS_MT WHERE ALIMENTADOR=NEW.ALIMENTADOR AND NODO=NEW.NODO AND ESTADO_REGISTRO='ALTA' LIMIT 1),
                        'ANALISIS EN BT DIRECTO'
                    )
                WHERE id=NEW.id;
            END;

CREATE TRIGGER trg_sbt_upd
            AFTER UPDATE ON SOSPECHAS_BT BEGIN
                UPDATE SOSPECHAS_BT SET
                    PERIODO_PLANIF=COALESCE((SELECT MES_PLANIFICADO FROM ALIMENTADORES WHERE ALIMENTADOR=NEW.ALIMENTADOR), ''),
                    ESTADO_RE=COALESCE(
                        (SELECT ESTADO_ACTIVIDAD FROM SOSPECHAS_MT WHERE ALIMENTADOR=NEW.ALIMENTADOR AND NODO=NEW.NODO AND ESTADO_REGISTRO='ALTA' LIMIT 1),
                        'ANALISIS EN BT DIRECTO'
                    )
                WHERE id=NEW.id;
            END;

CREATE TRIGGER trg_smt_del AFTER DELETE ON SOSPECHAS_MT BEGIN
            UPDATE ALIMENTADORES SET NODOS_SOSPECHOSOS=(SELECT COUNT(*) FROM SOSPECHAS_MT WHERE ALIMENTADOR=OLD.ALIMENTADOR AND ESTADO_REGISTRO='ALTA')
            WHERE ALIMENTADOR=OLD.ALIMENTADOR;
            UPDATE SOSPECHAS_BT SET ESTADO_RE=COALESCE(
                (SELECT ESTADO_ACTIVIDAD FROM SOSPECHAS_MT WHERE ALIMENTADOR=OLD.ALIMENTADOR AND NODO=OLD.NODO AND ESTADO_REGISTRO='ALTA' LIMIT 1),
                'ANALISIS EN BT DIRECTO'
            ) WHERE ALIMENTADOR=OLD.ALIMENTADOR AND NODO=OLD.NODO;
        END;

CREATE TRIGGER trg_smt_ins
            AFTER INSERT ON SOSPECHAS_MT BEGIN
                UPDATE ALIMENTADORES SET NODOS_SOSPECHOSOS=(SELECT COUNT(*) FROM SOSPECHAS_MT WHERE ALIMENTADOR=NEW.ALIMENTADOR AND ESTADO_REGISTRO='ALTA')
                WHERE ALIMENTADOR=NEW.ALIMENTADOR;
                UPDATE SOSPECHAS_MT SET PERIODO_PLANIF=(SELECT MES_PLANIFICADO FROM ALIMENTADORES WHERE ALIMENTADOR=NEW.ALIMENTADOR)
                WHERE id=NEW.id;
                UPDATE SOSPECHAS_BT SET ESTADO_RE=COALESCE(
                    (SELECT ESTADO_ACTIVIDAD FROM SOSPECHAS_MT WHERE ALIMENTADOR=NEW.ALIMENTADOR AND NODO=NEW.NODO AND ESTADO_REGISTRO='ALTA' LIMIT 1),
                    'ANALISIS EN BT DIRECTO'
                ) WHERE ALIMENTADOR=NEW.ALIMENTADOR AND NODO=NEW.NODO;
            END;

CREATE TRIGGER trg_smt_upd
            AFTER UPDATE ON SOSPECHAS_MT BEGIN
                UPDATE ALIMENTADORES SET NODOS_SOSPECHOSOS=(SELECT COUNT(*) FROM SOSPECHAS_MT WHERE ALIMENTADOR=NEW.ALIMENTADOR AND ESTADO_REGISTRO='ALTA')
                WHERE ALIMENTADOR=NEW.ALIMENTADOR;
                UPDATE SOSPECHAS_MT SET PERIODO_PLANIF=(SELECT MES_PLANIFICADO FROM ALIMENTADORES WHERE ALIMENTADOR=NEW.ALIMENTADOR)
                WHERE id=NEW.id;
                UPDATE SOSPECHAS_BT SET ESTADO_RE=COALESCE(
                    (SELECT ESTADO_ACTIVIDAD FROM SOSPECHAS_MT WHERE ALIMENTADOR=NEW.ALIMENTADOR AND NODO=NEW.NODO AND ESTADO_REGISTRO='ALTA' LIMIT 1),
                    'ANALISIS EN BT DIRECTO'
                ) WHERE ALIMENTADOR=NEW.ALIMENTADOR AND NODO=NEW.NODO;
            END;
